# Generated by Django 4.0.3 on 2022-03-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interno", "0001_crear_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Especie",
                "verbose_name_plural": "especies",
                "db_table": "especies",
            },
        ),
        migrations.CreateModel(
            name="FechaDePesca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("fecha", models.DateField(blank=True, default=None, null=True)),
                ("orden", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "verbose_name": "Fecha de pesca",
                "verbose_name_plural": "fechas de pesca",
                "db_table": "fechas_de_pesca",
            },
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "apellido",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "participantes",
                "db_table": "participantes",
            },
        ),
        migrations.CreateModel(
            name="Torneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Torneo",
                "verbose_name_plural": "torneos",
                "db_table": "torneos",
            },
        ),
        migrations.CreateModel(
            name="ResultadoFecha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_cupo", models.TimeField(blank=True, default=None, null=True)),
                ("pieza_mayor", models.FloatField(blank=True, default=0, null=True)),
                (
                    "puntaje_obtenido",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "fecha_de_pesca",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_fecha",
                        to="interno.fechadepesca",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_fecha",
                        to="interno.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado fecha",
                "verbose_name_plural": "resultados fecha",
                "db_table": "resultados_fecha",
            },
        ),
        migrations.CreateModel(
            name="InscripcionTorneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_torneo",
                        to="interno.participante",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_torneo",
                        to="interno.torneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripcion Torneo",
                "verbose_name_plural": "inscripciones torneo",
                "db_table": "inscripciones_torneo",
            },
        ),
        migrations.AddField(
            model_name="fechadepesca",
            name="torneo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fechas_de_pesca",
                to="interno.torneo",
            ),
        ),
        migrations.CreateModel(
            name="EspecieResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "especie",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especies_resultados",
                        to="interno.especie",
                    ),
                ),
                (
                    "resultado_fecha",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especies_resultados",
                        to="interno.resultadofecha",
                    ),
                ),
            ],
            options={
                "verbose_name": "EspecieResultado",
                "verbose_name_plural": "especies_resultados",
                "db_table": "especies_resultados",
            },
        ),
        migrations.CreateModel(
            name="EspeciePorFecha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "especie",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especies_por_fecha",
                        to="interno.especie",
                    ),
                ),
                (
                    "fecha_de_pesca",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especies_por_fecha",
                        to="interno.fechadepesca",
                    ),
                ),
            ],
            options={
                "verbose_name": "EspeciePorFecha",
                "verbose_name_plural": "especies_por_fecha",
                "db_table": "especies_por_fecha",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="interno.torneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "categorias",
                "db_table": "categorias",
            },
        ),
    ]
