# Generated by Django 4.0.3 on 2022-03-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interno", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscripciontorneo",
            name="torneo",
        ),
        migrations.AddField(
            model_name="inscripciontorneo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interno.categoria",
            ),
        ),
    ]
