# Generated by Django 4.0.3 on 2022-03-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0003_remove_inscripciontorneo_torneo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nombre'], 'verbose_name': 'Especie', 'verbose_name_plural': 'especies'},
        ),
        migrations.AlterModelOptions(
            name='fechadepesca',
            options={'ordering': ['orden'], 'verbose_name': 'Fecha de pesca', 'verbose_name_plural': 'fechas de pesca'},
        ),
        migrations.AlterModelOptions(
            name='inscripciontorneo',
            options={'ordering': ['categoria__torneo', 'categoria__nombre'], 'verbose_name': 'Inscripcion Torneo', 'verbose_name_plural': 'inscripciones torneo'},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Participante', 'verbose_name_plural': 'participantes'},
        ),
    ]
